[package]
name = "chrysanthemum"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5"
dotenv = "0.15"
log = "0.4"
pretty_env_logger = "0.4"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_regex = "1.1"
discordant = { path = "../discordant" }
once_cell = "1.8"
time = "0.2"
ctrlc = { version = "3", features = ["termination"] }

[patch.crates-io]
serde = { path = "../serde/serde", features = ["derive"] }
